
#=====================================================================
#   Ansible Inventory - my defaults
#   Updated with GCP hosts
#
#=====================================================================

# Linux nodes for general use
[clients]
client01.gcp ansible_host=10.129.1.37
client02.gcp ansible_host=10.129.1.32
client03.gcp ansible_host=10.129.1.35
client04.gcp ansible_host=10.129.1.29
client05.gcp ansible_host=10.129.1.30
client06.gcp ansible_host=10.129.1.34
client07.gcp ansible_host=10.129.1.36
client08.gcp ansible_host=10.129.1.28
client09.gcp ansible_host=10.129.1.31
client10.gcp ansible_host=10.129.1.33
client11.gcp ansible_host=10.129.1.44
client12.gcp ansible_host=10.129.1.38
client13.gcp ansible_host=10.129.1.40
client14.gcp ansible_host=10.129.1.39
client15.gcp ansible_host=10.129.1.47
client16.gcp ansible_host=10.129.1.41
client17.gcp ansible_host=10.129.1.45
client18.gcp ansible_host=10.129.1.46
client19.gcp ansible_host=10.129.1.42
#client20.gcp ansible_host=10.129.1.43


[clients:vars]
ansible_ssh_private_key_file=~/.ssh/admin_keys/labkey
ansible_ssh_user=labuser

# Proxy Node
[proxy]
proxyvm01

[proxy:vars]
ansible_ssh_user=labuser

# VAST Cluster
#[cnode]
#10.100.2.72
#10.100.2.105
#10.100.2.106

#[cnode:vars]
#ansible_ssh_user=centos

### For settingi up Trino
#[trino_coordinator]
#client11
#
#[trino_workers]
#client10
#client09
#client08

#[trino:children]
#trino_coordinator
#trino_workers

#[trino:vars]
#ansible_ssh_user=labuser


#====================================================================#
# For all hosts - per group overrides this
#====================================================================#

[all:vars]
ansible_ssh_user=root
ansible_python_interpreter="/usr/bin/python3"
