---
### File - site.yml
#   Top level playbook
#   
#   Created By:   Karl Vietmeier
#

- hosts: all
  roles:
     - bootstrap
     - kubernetes
  remote_user: root
  vars_files:
     # Any confidential info like certs, keys, etc.
     - group_vars/private_vars.yml

...
