---
### File - site.yml
#   Setup ATC Servers
#   
#   Created By:   Karl Vietmeier
#

- hosts: centosvms
  remote_user: vagrant
  roles:
     - common
  remote_user: vagrant
  sudo: yes

- hosts: ubuntuvms
  remote_user: vagrant
  roles:
     - common
  remote_user: vagrant
  sudo: yes

