---
### File - site.yml
#   Top level playbook for VAST NFS Client Installation
#   
#   Created By:   Karl Vietmeier
#  
- name: Setup VAST NFS Client Environment
  hosts: clients
  become: true

  roles:
    - role: vast_client
      tags: ['never', 'base', 'client']
    
    - role: vast_nfs
      tags: ['never', 'install_driver']
    
    #- role: specsfs