---
### File - site.yml
#   Top level playbook to "bootstrap" servers
#   
#   Created By:   Karl Vietmeier
#

- hosts: centosvms:ubuntuvms
  remote_user: vagrant
  roles:
     - common
  remote_user: vagrant
  sudo: yes
