# =============================================================================
# build.yml – Build VAST NFS driver
#
# Description:
#   Runs build.sh to compile driver into binary packages. Skips rebuild if
#   dist folder already exists.
#
# Tags:
#   [build]
# =============================================================================
---
- name: Log build prep
  shell: |
    echo "Preparing to build in {{ nfs_version_dir }}" >> {{ output_log }}
    ls -la "/root/{{ nfs_version_dir }}" >> {{ output_log }}
  args:
    executable: /bin/bash

- name: Check if build output exists
  stat:
    path: "/root/{{ nfs_version_dir }}/dist"
  register: dist_check

- name: Run build.sh (bin) if needed
  shell: |
    ./build.sh bin >> {{ output_log }} 2>&1
    echo "build.sh completed with exit code $?" >> {{ output_log }}
  args:
    chdir: "/root/{{ nfs_version_dir }}"
    executable: /bin/bash
  when: not dist_check.stat.exists

- name: Find built package
  find:
    paths: "/root/{{ nfs_version_dir }}/dist"
    patterns: "vastnfs-*"
    recurse: no
  register: found_pkgs
