# =============================================================================
# main.yml – Master task flow for VAST NFS driver role
#
# Description:
#   Orchestrates all steps: prerequisites, download, build, install, and verify
#   for the VAST NFS kernel driver. 
#   Compatible with both Debian/Ubuntu and RHEL/CentOS systems; included 
#   task files handle OS-specific package managers, kernel header paths, 
#   and module installation differences.
#
# Usage:
#   Run entire flow or target specific sections using tags:
#     - prereqs
#     - download
#     - build
#     - install
#     - verify
#
# Notes:
#   The mountprep task is excluded by default as it is recommended to run it
#   manually after installation, outside Ansible. It is kept here for archival reasons.
# =============================================================================
---
# Orchestrates the full driver installation

- include_tasks: prereqs.yml
  tags: [prereqs]

- include_tasks: download.yml
  tags: [download]

- include_tasks: build.yml
  tags: [build]

- include_tasks: install.yml
  tags: [install]

- include_tasks: verify.yml
  tags: [verify]

# Don't need this - better to run it manually after the install outside Ansible
# Leaving here for archival reasons.
#- include_tasks: mountprep.yml
#  tags: [mountprep]
