# =============================================================================
# mountprep.yml – Prepare mount point and save mount command
#
# Description:
#   Creates NFS mount point directory and writes a ready-to-run mount command
#   to /usr/local/bin/nfs_mount_cmd.txt for manual or automated use.
#
# Tags:
#   [mountprep], optional [mount_now] executes the mount immediately
# =============================================================================
---
- name: Ensure NFS mount point exists
  file:
    path: "{{ mount_point }}"
    state: directory
    mode: '0777'

- name: Save NFS mount command to text file
  copy:
    content: |
      mount -t nfs -o proto=tcp,vers=3,nconnect={{ conns }},remoteports={{ port_range }} \
      {{ dns_alias }}.{{ dns_domain }}.org:/{{ view_path }} {{ mount_point }}
    dest: /usr/local/bin/nfs_mount_cmd.txt
    mode: '0644'

#- name: Execute NFS mount command immediately (optional)
#  shell: |
#    mount -t nfs -o proto=tcp,vers=3,nconnect={{ conns }},remoteports={{ port_range }} \
#    {{ dns_alias }}.{{ dns_domain }}.org:/{{ view_path }} {{ mount_point }}
#  tags: [mount_now]
