---
# File: roles/kubernetes/handlers/main.yml
# Handlers for common services
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.

# Services
- name: restart ntpd
  ansible.builtin.service:
    name: ntpd
    state: restarted

- name: restart iptables
  ansible.builtin.service:
    name: iptables
    state: restarted

# Wait for a server after reboot
- name: Wait for restart
  local_action:
    module: wait_for
      host={{ inventory_hostname }}
      port=22
      delay=10
      #timeout=300
    sudo: false

# Is docker running?
- name: Docker status
  ansible.builtin.service:
    name: docker
    state: started

...

