---
### File - dockersetup.yml
#   https://kubernetes.io/blog/2019/03/15/kubernetes-setup-using-ansible-and-vagrant/
#   Created By:   Karl Vietmeier
#
###

- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ apt_html_pkgs }}"
    state: present
    update_cache: yes
  tags: 
    - docker

- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: 
    - docker

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
  tags: 
    - docker

- name: Install docker and its dependecies
  apt: 
    name: "{{ docker_pkgs }}"
    state: present
    update_cache: yes
  notify:
    - docker status
  tags: 
    - docker

- name: Set Docker to use systemd for container mgmt
  ansible.builtin.lineinfile:
    path: /etc/docker/daemon.json
    line: { "exec-opts": ["native.cgroupdriver=systemd"] }
    create: yes

- name: Add kube user to docker group
  user:
    name: kube
    group: docker
  tags: 
    - docker
