---
### File - dockersetup.yml
#   https://kubernetes.io/blog/2019/03/15/kubernetes-setup-using-ansible-and-vagrant/
#   Created By:   Karl Vietmeier
#
###

- name: Install packages that allow apt to be used over HTTPS
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: yes
  tags: 
    - docker

- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: 
    - docker

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
  tags: 
    - docker

- name: Install docker and its dependecies
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io
  notify:
    - docker status
  tags: 
    - docker

- name: Add kube user to docker group
  user:
    name: kube
    group: docker
  tags: 
    - docker
