---
# File roles/kubernetes/tasks/main.yml

# Install K8S packages
- include: dockersetup.yml

# Configure systems
- include: k8ssetup.yml

# Create cluster
- include: initializecluster.yml 

# ......
- include: join_node.yml

# ......
#- include: foobar5.yml


...
