---
# File: roles/common/tasks/install_pkgs.yml
# Update system and install extra packages

- name: install the 'Development tools' package group
  yum: name="@Development tools" state=present
  tags:
     - yum

- name: Install Bunch of Useful Packages
  yum: name={{ item }} state=installed
  with_items: "{{xtra_pkgs}}"
  tags:
     - yum

- name: Upgrade all packages
  yum: name=* state=latest
  tags:
     - yum

...
