---
# File: roles/common/tasks/install_pkgs.yml
# Update system and install extra packages

# RHEL/Centos
- name: Install the RHEL/Centos 'Development Tools' package group
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  yum: name="@Development tools" state=present
  tags:
     - pkgs

- name: Install Bunch of Useful Packages
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  yum: name={{ item }} state=installed
  with_items: "{{xtra_pkgs}}"
  tags:
     - pkgs

- name: Upgrade all packages
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  yum: name=* state=latest
  tags:
     - pkgs


# Ubuntu 
- name: Update Ubuntu System
  when: ansible_distribution == 'Ubuntu'
  apt: update_cache=yes
  tags: pkgs

- name: Upgrade Ubuntu System
  when: ansible_distribution == 'Ubuntu'
  apt: upgrade=dist
  tags: pkgs

- name: Install Ubuntu Development Tools
  when: ansible_distribution == 'Ubuntu'
  apt: name=build-essential state=present
  tags: pkgs

- name: Upgrade all Ubuntu packages
  yum: name=* state=latest
  tags:
     - pkgs


# All Distros
- name: Update Man Page Database
  command: mandb
  tags: pkgs

