---
# File: roles/common/tasks/install_pkgs.yml
# Update system and install extra packages

# Upgrade RHEL/Centos Based Systems
- name: "RHEL: Install the RHEL/Centos 'Development Tools' package group"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  yum: name="@Development tools" state=present
  tags:
     - pkgs

- name: "RHEL: Install a Bunch of Useful Packages you will need eventually"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  yum: name={{ item }} state=present
  with_items: "{{xtra_pkgs}}"
  tags:
     - pkgs

- name: "RHEL: Install RHEL Specific Useful Packages"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  yum: name={{ item }} state=present
  with_items: "{{rhel_pkgs}}"
  tags:
     - pkgs

- name: "RHEL: Upgrade all packages"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  yum: name=* state=latest
  tags:
     - pkgs


# Upgrade Debian/Ubuntu based systems and reboot if necessary.
- name: "Ubuntu: Install Ubuntu Development Tools"
  when: ansible_distribution == 'Ubuntu'
  apt: name=build-essential state=present
  tags: pkgs

- name: "Ubuntu: Install Bunch of Useful Packages"
  when: ansible_distribution == 'Ubuntu'
  apt: name={{ item }} state=present
  with_items: "{{xtra_pkgs}}"
  tags: pkgs

- name: "Ubuntu: Check if there are packages available to be installed/upgraded"
  when: ansible_distribution == 'Ubuntu'
  command: /usr/lib/update-notifier/apt-check --package-names
  register: packages
  tags: pkgs

- name: "Ubuntu: Upgrade all packages to the latest version"
  when: (ansible_distribution == 'Ubuntu') and (packages.stderr != "")
  apt: update_cache=yes upgrade=dist
  tags: pkgs


# All Distros
- name: "All: Update Man Page Database"
  command: mandb
  tags: pkgs


# Reboot Ubuntu server if required (because Ubuntu is lame)
- name: "Ubuntu: Check if a reboot is required"
  when: ansible_distribution == 'Ubuntu'
  register: file
  stat: path=/var/run/reboot-required get_md5=no
  tags: pkgs

- name: "Ubuntu: Reboot the server"
  when: (ansible_distribution == 'Ubuntu') and (file.stat.exists == true)
  command: /sbin/reboot
  tags: pkgs


