---
# File roles/common/tasks/main.yml

# Checkl some basic parameters to see if we should even proceed.
- include: check_os.yml

# Red Hat Subscription Management
- include: rh_register.yml

# Setup Users Environment
- include: user_config.yml 

# Setup ntp
- include: ntp.yml

# Run yum, update packages
- include: install_pkgs.yml


...
