---
# File roles/common/tasks/ntp.yml
# Install and configure ntp


# Setup ntp
- name: Be sure ntp is installed
  yum: name=ntp state=installed
  tags: ntp

- name: Set the correct timezone.
  file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    state: link
    force: yes

#- name: Be sure ntp is configured
#  template: src=ntp.conf.j2 dest=/etc/ntp.conf
#  notify:
#    - restart ntpd
#  tags: ntp

- name: Run ntpdate to set the correct time/date
  command: /sbin/ntpdate 0.centos.pool.ntp.org
  tags: ntp  

- name: Be sure ntpd is running and enabled
  service: name=ntpd state=running enabled=yes
  tags: ntp

...
