---
# File roles/common/tasks/user_config.yml
# Basic user related configuration items

# Setup some basic functionality for users and sudo

#--- Remove the requiretty directive from /etc/sudoers
- name: Remove requiretty
  lineinfile: dest=/etc/sudoers regexp="^Defaults.*requiretty" line='Defaults !requiretty'  backup=yes state=present validate='visudo -cf %s'
  become: yes
  become_method: sudo
  tags:
     - usercfg


#--- SSH Keys
- name: Copy rsa keys to user root
  authorized_key: user=root key="{{ item }}"
  become: yes
  become_method: sudo
  with_file:
    - roles/common/files/auth/skarn.id_rsa.pub
    - roles/common/files/auth/foobar.id_rsa.pub
  tags:
     - usercfg



###
# Sudoers file stuff -

## Allows people in group wheel to run all commands
#%wheel  ALL=(ALL)       ALL

## Same thing without a password
# %wheel        ALL=(ALL)       NOPASSWD: ALL

# this specifically calls outr a user rather than hte group - probably safer.
#vagrant ALL=(ALL) NOPASSWD:ALL

# Not sure the above will work in all cases if the Defaults line is commented out 
# Defaults    requiretty


# Fully quoted because of the ': ' on the line. See the Gotchas in the YAML docs.
#- lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL'"


# Validate the sudoers file before saving
#- lineinfile: dest=/etc/sudoers 
#      state=present 
#      regexp='^%ADMIN ALL\=' 
#      line='%ADMIN ALL=(ALL) NOPASSWD:ALL' 
####--->      validate='visudo -cf %s'










...
