---
# File roles/common/tasks/user_config.yml
# Basic user related configuration items

# Setup some basic functionality for users and sudo

#--- Remove the requiretty directive from /etc/sudoers
- name: Remove requiretty
  lineinfile: dest=/etc/sudoers regexp="^Defaults.*requiretty" line='Defaults !requiretty'  backup=yes state=present validate='visudo -cf %s'
  become: yes
  become_method: sudo
  tags:
     - usercfg

- name: Enable wheel group in Centos/RHEL to issue all commands with NOPASSWD
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  lineinfile: "dest=/etc/sudoers state=present backup=yes regexp='^%wheel.*NOPASSWD' line='%wheel ALL=(ALL) NOPASSWD: ALL' validate='visudo -cf %s'"
  become: yes
  become_method: sudo
  tags:
     - usercfg

- name:  Remove wheel lines in Ubuntu sudoers - remove when done testing
  when: ansible_distribution == 'Ubuntu'
  lineinfile: "dest=/etc/sudoers state=absent backup=yes regexp='^%wheel.*NOPASSWD' line='%wheel ALL=(ALL) NOPASSWD: ALL' validate='visudo -cf %s'"
  become: yes
  become_method: sudo
  tags:
     - usercfg


#--- SSH Keys
- name: Copy rsa keys to user root
  authorized_key: user=root key="{{ item }}"
  become: yes
  become_method: sudo
  with_file:
    - roles/common/files/auth/skarn.id_rsa.pub
    - roles/common/files/auth/foobar.id_rsa.pub
  tags:
     - usercfg


# Validate the sudoers file before saving
#- lineinfile: dest=/etc/sudoers 
#      state=present 
#      regexp='^%ADMIN ALL\=' 
#      line='%ADMIN ALL=(ALL) NOPASSWD:ALL' 
####--->      validate='visudo -cf %s'










...
