---
# tasks/disable_upgrades.yml
# =============================================================================
# Disable unattended-upgrades and automatic APT timers
#
# Description:
#   Stops, disables, and masks the unattended-upgrades service.
#   Stops and disables apt daily timers.
#   Disables periodic package updates via apt configuration.
#
# Tags:
#   [prereqs]
# =============================================================================

- name: Ensure unattended-upgrades services are stopped, disabled, and masked
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    masked: yes
  loop:
    - unattended-upgrades
    - apt-daily.service
    - apt-daily-upgrade.service

- name: Stop and disable apt timers
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop:
    - apt-daily.timer
    - apt-daily-upgrade.timer

- name: Disable periodic apt updates via config file
  copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "0";
      APT::Periodic::Unattended-Upgrade "0";
    owner: root
    group: root
    mode: '0644'
