# =============================================================================
# download.yml – Download and extract VAST NFS driver
#
# Description:
#   Uses official download script to fetch driver tarball, locates tarball,
#   and extracts to /root. Prepares for build phase.
#
# Tags:
#   [download]
# =============================================================================
---
- name: Run VAST NFS download script and capture filename
  shell: |
    set -o pipefail
    filename=$(curl -sSf {{ download_script_url }} | bash -s -- --print-url | xargs basename)
    echo "$filename"
  args:
    chdir: /root
    executable: /bin/bash
  register: download_result

- name: Set tarball and version directory facts
  set_fact:
    nfs_tarball: "{{ download_result.stdout }}"
    nfs_version_dir: "{{ download_result.stdout | regex_replace('\\.tar\\.xz$', '') }}"

- name: Remove existing extracted folder if it exists
  file:
    path: "/root/{{ nfs_version_dir }}"
    state: absent

- name: Extract the downloaded tarball
  unarchive:
    src: "/root/{{ nfs_tarball }}"
    dest: /root
    remote_src: yes

- name: Example - use the tarball in another task
  debug:
    msg: "The downloaded tarball is {{ nfs_tarball }} and will be extracted to {{ nfs_version_dir }}"

- name: Example - compile or install using the extracted directory
  shell: |
    cd /root/{{ nfs_version_dir }}
    ./configure && make && make install
  args:
    executable: /bin/bash
