---
# tasks/prereqs.yml
# =============================================================================
# Prerequisite checks and environment prep
#
# Description:
#   Waits for cloud-init completion, sets OS family facts, installs GCC for
#   Ubuntu, disables unattended-upgrades, and ensures /root exists.
#   Prepares environment for driver build.
#
# Tags:
#   [prereqs]
# =============================================================================

- name: Set OS family flags
  set_fact:
    is_redhat: "{{ ansible_facts['distribution'] in ['RedHat', 'CentOS', 'Rocky', 'AlmaLinux'] }}"
    is_ubuntu: "{{ ansible_facts['distribution'] == 'Ubuntu' }}"

# -------------------------------------------------------------------
# Cloud-init wait
# -------------------------------------------------------------------
- name: Check cloud-init service
  systemd:
    name: cloud-init
  register: cloudinit_status
  failed_when: false
  changed_when: false

- name: Wait for cloud-init to finish
  wait_for:
    path: /var/lib/cloud/instance/boot-finished
    state: present
    timeout: 600
  when: cloudinit_status.status is defined and cloudinit_status.status.ActiveState == 'active'

# -------------------------------------------------------------------
# Root directory prep
# -------------------------------------------------------------------
- name: Ensure /root directory exists
  file:
    path: /root
    state: directory

# -------------------------------------------------------------------
# Disable unattended-upgrades on Debian/Ubuntu
# -------------------------------------------------------------------
- include_tasks: disable_upgrades.yml
  when: is_ubuntu
  tags: [prereqs]

# -------------------------------------------------------------------
# GCC installation on Ubuntu
# -------------------------------------------------------------------
- name: Install GCC 12 and set default (Ubuntu only)
  block:
    - name: Install GCC 12
      apt:
        name:
          - gcc-12
          - g++-12
        state: present
        update_cache: yes

    - name: Set GCC 12 as default
      shell: |
        update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100
        update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 100
  when: is_ubuntu
